apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: jellyfin
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/part-of: jellyfin
  ports:
    - name: http
      port: 8096
      targetPort: 8096
      protocol: TCP
