apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaresolverr
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/part-of: flaresolverr
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/name: flaresolverr
      app.kubernetes.io/part-of: flaresolverr
  template:
    metadata:
      labels:
        app.kubernetes.io/managed-by: kustomize
        app.kubernetes.io/name: flaresolverr
        app.kubernetes.io/part-of: flaresolverr
    spec:
      nodeSelector:
        kubernetes.io/hostname: pj
      containers:
        - name: tor
          image: osminogin/tor-simple:latest
          ports:
            - name: socks
              containerPort: 9050
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          ports:
            - name: http
              containerPort: 8191
          env:
            - name: TZ
              value: "Europe/Berlin"
            - name: LOG_LEVEL
              value: "info"
            - name: PROXY_URL
              value: "socks5://localhost:9050"
          resources:
            requests:
              cpu: 100m
              memory: 512Mi
            limits:
              cpu: "2"
              memory: 1536Mi
