apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/part-of: flaresolverr
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: flaresolverr
    app.kubernetes.io/part-of: flaresolverr
  ports:
    - name: http
      port: 8191
      targetPort: 8191
      protocol: TCP
