apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arr-stack
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: arr-stack
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: qbit.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack
                port:
                  number: 8080
    - host: sabnzbd.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack
                port:
                  number: 8085
    - host: prowlarr.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack
                port:
                  number: 9696
    - host: sonarr.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack
                port:
                  number: 8989
    - host: radarr.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack
                port:
                  number: 7878
    - host: bazarr.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arr-stack
                port:
                  number: 6767
    - host: jellyseerr.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jellyseerr
                port:
                  number: 5055
