apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr-stack

resources:
  - pvcs.yaml
  - nas-pvc.yaml
  - deployment.yaml
  - services.yaml
  - ingress.yaml
  - sealed-secrets.yaml
