apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: arr-stack

resources:
  - deployment.yaml
  - services.yaml
  - ingress.yaml
  - pvc.yaml
  # secrets.yaml - apply manually, don't commit to git!
