apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  labels:
    app: arr-stack
spec:
  selector:
    app: arr-stack
  ports:
    - port: 8080
      targetPort: 8080
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: sonarr
  labels:
    app: arr-stack
spec:
  selector:
    app: arr-stack
  ports:
    - port: 8989
      targetPort: 8989
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: arr-stack
spec:
  selector:
    app: arr-stack
  ports:
    - port: 7878
      targetPort: 7878
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: arr-stack
spec:
  selector:
    app: arr-stack
  ports:
    - port: 9696
      targetPort: 9696
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: jellyseerr
  labels:
    app: arr-stack
spec:
  selector:
    app: arr-stack
  ports:
    - port: 5055
      targetPort: 5055
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  labels:
    app: arr-stack
spec:
  selector:
    app: arr-stack
  ports:
    - port: 8191
      targetPort: 8191
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: bazarr
  labels:
    app: arr-stack
spec:
  selector:
    app: arr-stack
  ports:
    - port: 6767
      targetPort: 6767
      name: http
