apiVersion: v1
kind: Service
metadata:
  name: vikunja
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/part-of: vikunja
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vikunja
    app.kubernetes.io/part-of: vikunja
  ports:
    - name: http
      port: 3456
      targetPort: 3456
      protocol: TCP
