apiVersion: apps/v1
kind: Deployment
metadata:
  name: threadfin
  labels:
    app.kubernetes.io/name: threadfin
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: threadfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: threadfin
    spec:
      enableServiceLinks: false
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command: ["sh", "-c", "chown -R 31337:31337 /home/threadfin/conf"]
          volumeMounts:
            - name: config
              mountPath: /home/threadfin/conf
      containers:
        - name: threadfin
          image: fyb3roptik/threadfin:1.1.36
          env:
            - name: TZ
              value: "Europe/Vienna"
          ports:
            - name: http
              containerPort: 34400
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          volumeMounts:
            - name: config
              mountPath: /home/threadfin/conf
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: threadfin-config
