apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: threadfin
  labels:
    app.kubernetes.io/name: threadfin
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: threadfin.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: threadfin
                port:
                  number: 34400
    - host: threadfin.pj-home-lab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: threadfin
                port:
                  number: 34400
