apiVersion: v1
kind: Service
metadata:
  name: threadfin
  labels:
    app.kubernetes.io/name: threadfin
spec:
  type: ClusterIP
  ports:
    - port: 34400
      targetPort: 34400
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: threadfin
