apiVersion: v1
kind: Service
metadata:
  name: whisper
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whisper
    app.kubernetes.io/part-of: whisper
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: whisper
    app.kubernetes.io/part-of: whisper
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
