apiVersion: v1
kind: Service
metadata:
  name: mealie
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mealie
    app.kubernetes.io/part-of: mealie
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: mealie
    app.kubernetes.io/part-of: mealie
  ports:
    - name: http
      port: 9000
      targetPort: 9000
      protocol: TCP
