apiVersion: v1
kind: Service
metadata:
  name: ollama
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ollama
    app.kubernetes.io/part-of: ollama
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: ollama
    app.kubernetes.io/part-of: ollama
  ports:
    - name: http
      port: 11434
      targetPort: 11434
      protocol: TCP
