apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base.yaml
  - secrets.yaml
  - immich.yaml
  - monitoring.yaml
  - cloudflare.yaml
  - woodpecker.yaml
  - vikunja.yaml
  - jellyfin.yaml
  - it-tools.yaml
  - arr-stack.yaml
  - threadfin.yaml
