apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: it-tools
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: it-tools
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: it-tools.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: it-tools
                port:
                  number: 80
    - host: tools.pj-home-lab.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: it-tools
                port:
                  number: 80
