apiVersion: v1
kind: Service
metadata:
  name: it-tools
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: it-tools
    app.kubernetes.io/part-of: it-tools
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: it-tools
    app.kubernetes.io/part-of: it-tools
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
