apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: card-sniper
  labels:
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/part-of: card-sniper
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  ingressClassName: traefik
  rules:
    - host: card-sniper.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: card-sniper
                port:
                  number: 8000
